#!/bin/sh
#PBS -l nodes=4:G1
#PBS -l walltime=200:00:00
#PBS -N MAPI
### queue list: defaultq
#PBS -q defaultq
### Declare job non-rerunable
#PBS -r n
### Output files
#PBS -o ./
#PBS -e ./
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
NEW_NODEFILE=`mktemp`
gen.nodefile $PBS_NODEFILE $NEW_NODEFILE
NP=`/usr/bin/wc -l $NEW_NODEFILE | awk '{print $1}'`

MPIRUN="$I_MPI_ROOT/intel64/bin/mpirun -machinefile $NEW_NODEFILE -np $NP "
$MPIRUN ./unfold.x < unfold.in >& unfold.out

exit 0 
