#!/bin/sh
#PBS -l nodes=8:G4
#PBS -l walltime=200:00:00
#PBS -N test
### queue list: defaultq
#PBS -q defaultq
### Declare job non-rerunable
#PBS -r n
### Output files
#PBS -o ./
#PBS -e ./
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
NEW_NODEFILE=`mktemp`
gen.nodefile $PBS_NODEFILE $NEW_NODEFILE
NP=`/usr/bin/wc -l $NEW_NODEFILE | awk '{print $1}'`

MPIRUN="$I_MPI_ROOT/intel64/bin/mpirun -machinefile $NEW_NODEFILE -np $NP "
# $MPIRUN /lily/ywchoe/codes/qe/6.4.1/bin/pw.x -nk 10 -i pw.in >& pw.out
$MPIRUN /lily/ywchoe/codes/qe/6.4.1/bin/pw.x -nk 16 -i pw.bands.in >& pw.bands.out
$MPIRUN ../../unfold.x -i unfold.in >& unfold.out

exit 0 
